#!/bin/bash

set -x

if [[ "$(uname)" == 'Darwin' ]]; then
  OS='Mac'
elif [[ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]]; then
  OS='Linux'
elif [[ "$(expr substr $(uname -s) 1 10)" == 'MINGW32_NT' ]]; then
  OS='Cygwin'
  echo "Your platform (${OS}) is not supported."
  exit 1
else
  echo "Your platform ($(uname -a)) is not supported."
  exit 1
fi

case "${OS}"; in
  'Linux' )
    regolith/setup
    ;;
  'Mac' )
    bin/setup
    zsh/setup
    gdb/setup
    nvim/setup
    latex/setup
    break
    ;;
esac

