[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.config/nvim/plugins/denite.vim'

# deoplete
# ---
#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#hook_add = 'source ~/.config/nvim/plugins/deoplete.vim'

#[[plugins]] 
#repo = 'roxma/nvim-yarp'

#[[plugins]] 
#repo = 'roxma/vim-hug-neovim-rpc'

#[[plugins]] 
#repo = 'deoplete-plugins/deoplete-lsp'

#[[plugins]] 
#repo = 'Shougo/deoplete-clangx'

#[[plugins]] 
#repo = 'deoplete-plugins/deoplete-asm'

#[[plugins]] 
#repo = 'deoplete-plugins/deoplete-jedi'

#[[plugins]] 
#repo = 'sebastianmarkow/deoplete-rust'
#hook_add = 'source ~/.config/nvim/plugins/deoplete-rust.vim'

#[[plugins]] 
#repo = 'Shougo/neco-vim'

#[[plugins]]
#repo = 'Shougo/neco-syntax'

#[[plugins]]
#repo = 'ujihisa/neco-look'
# ---

# coc
# ---
[[plugins]]
repo = 'neoclide/coc.nvim'


# ---

[[plugins]]
repo = 'rafi/awesome-vim-colorschemes'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'source ~/.config/nvim/plugins/fzf.vim'

[[plugins]]
repo = 'Townk/vim-autoclose'
hook_add = 'source ~/.config/nvim/plugins/autoclose.vim'

[[plugins]]
repo = 'iamcco/markdown-preview.vim'

[[plugins]]
repo = 'lervag/vimtex'
hook_add = 'source ~/.config/nvim/plugins/vimtex.vim'

[[plugins]]
repo = 'scrooloose/nerdTree'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source ~/.config/nvim/plugins/airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.config/nvim/plugins/ale.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source ~/.config/nvim/plugins/gitgutter.vim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = 'source ~/.config/nvim/plugins/anzu.vim'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'smancill/conky-syntax.vim'

[[plugins]]
repo = 'mattn/sonictemplate-vim'
hook_add = 'source ~/.config/nvim/plugins/sonictemplate.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'lighttiger2505/gtags.vim'

[[plugins]]
repo = 'jsfaint/gen_tags.vim'

[[plugins]]
repo = 'ozelentok/denite-gtags'

[[plugins]]
repo = 'ARM9/arm-syntax-vim'
hook_add = 'source ~/.config/nvim/plugins/arm-syntax.vim'

[[plugins]]
repo = 'segeljakt/vim-silicon'
hook_add = 'source ~/.config/nvim/plugins/silicon.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = 'source ~/.config/nvim/plugins/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'prettier/vim-prettier'

[[plugins]]
repo = 'kassio/neoterm'
hook_add = 'source ~/.config/nvim/plugins/neoterm.vim'
