[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = 'source ~/.config/nvim/plugins/deoplete.vim'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'source ~/.config/nvim/plugins/fzf.vim'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'Townk/vim-autoclose'
hook_add = 'source ~/.config/nvim/plugins/autoclose.vim'

[[plugins]]
repo = 'iamcco/markdown-preview.vim'

[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'scrooloose/nerdTree'

