[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.config/nvim/plugins/denite.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source ~/.config/nvim/plugins/airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.config/nvim/plugins/ale.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source ~/.config/nvim/plugins/gitgutter.vim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = 'source ~/.config/nvim/plugins/anzu.vim'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'smancill/conky-syntax.vim'
