#!/bin/bash

set -e

if [[ ! -e "${HOME}/.local/share/nvim/site/pack/packer/start/packer.nvim" ]];then
  git clone --depth 1 https://github.com/wbthomason/packer.nvim "${HOME}/.local/share/nvim/site/pack/packer/start/packer.nvim"
fi

if [[ ! -d "${HOME}/.config/nvim" ]];then
	mkdir "${HOME}/.config/nvim"
fi

ln -ivs "${PWD}/init.lua" "${HOME}/.config/nvim/init.lua"
ln -ivs "${PWD}/lua" "${HOME}/.config/nvim/lua"

