let g:silicon = {
			\ 'theme':'Nord',
			\ 'font': 'Hack',
			\ 'background':'#AAAAFF',
			\ 'shadow-color':'#555555',
			\ 'line-pad':0,
			\ 'pad-horiz':0,
			\ 'pad-vert':0,
			\ 'shadow-blur-radius':0,
			\ 'shadow-offset-x':0,
			\ 'shadow-offset-y':0,
			\ 'line-number':v:true,
			\ 'round-corner':v:false,
			\ 'window-controls':v:false,
			\ 'output':'~/OneDrive/lab/resources/silicon-{time:%Y-%m-%d-%H%M%S}.png',
			\ 'language':'C',
			\}
