#!/bin/bash

set -x
set -e

PWD=$(pwd)

function link_config() {
	CONFIG_FILE="${1}"
	ln -ivs "${PWD}/${CONFIG_FILE}" "${HOME}/.${CONFIG_FILE}"
}

if ! type sheldon > /dev/null 2>&1 ; then
	echo "sheldon is required but, not installed"
	exit 1
else
	ln -ivs "${PWD}/sheldon" "${HOME}/.config/sheldon"
fi

link_config zshrc
link_config zshenv
link_config zprofile
link_config zconfig

