#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
	source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# for go lang
	if [ -x "`which go`" ]; then
		export GOPATH=$HOME/go
		export PATH="$GOPATH/bin:$PATH"
	fi

export PATH="~/.gem/ruby/2.5.0/bin:$PATH"
export PATH="~/virtualenvs/zeratool/bin:$PATH"
