alias ls='lsd'
alias l='ls'
alias la='ls -a'
alias ll='ls -l'
alias	lla='ls -la'
alias lt='ls --tree'

alias ..='cd ./../'

alias cp='cp -i -p'
alias rm='rm -i'
alias mv='mv -i'
alias mkdir='mkdir -p'

alias vim='nvim'
alias open='xdg-open'
alias gdb='gdb -q'

alias q='exit'
alias c='clear'
alias x='chmod +x'
alias path='echo $PATH'

alias tar-compress-tgz='tar -cvzf'
alias tar-extract-tgz='tar -xvzf'
alias tar-compress-gz='tar -zcvf'
alias tar-extract-gz='tar -zxvf'
alias tar-compress-bz2='tar -jcvf'
alias tar-extract-bz2='tar -jxvf'
alias tar-compress-xz='tar -Jcvf'
alias tar-extract-xz='tar -Jxvf'
alias tar-compress-tar='tar -cvf'
alias tar-extract-tar='tar -xvf'

alias -g L='| less'
alias -g H='| head'
alias -g G='| ag'
alias -g F='| fzf'
alias -g C='| xsel --clipboard --input'

alias pip-review='pip freeze --local | grep -v "^\-e" | cut -d = -f 1  | xargs -n1 pip install -U'
alias pip2-review='pip2 freeze --local | grep -v "^\-e" | cut -d = -f 1  | xargs -n1 pip2 install -U'
alias pip3-review='pip3 freeze --local | grep -v "^\-e" | cut -d = -f 1  | xargs -n1 pip3 install -U'
